# Generated by Django 5.2.12 on 2026-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_alter_diseaseprediction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseprediction',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
