# Generated by Django 5.2.12 on 2026-04-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_alter_diseaseprediction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseprediction',
            name='image',
            field=models.ImageField(upload_to='disease_images/'),
        ),
    ]
